Repository AsdarDevelops/PokeRogue-Events, pull requests merged in 2024-08, with the labels that each got.

#128 Clowning around
  public/battle-anims/encounter-smokescreen.json
  public/images/mystery-encounters/encounter_radar.json
  public/images/mystery-encounters/exclaim.json
  src/battle-scene.ts
  src/data/battle-anims.ts
  src/data/mystery-encounters/encounters/an-offer-you-cant-refuse-encounter.ts
  src/data/mystery-encounters/encounters/clowning-around-encounter.ts
  src/data/mystery-encounters/encounters/dark-deal-encounter.ts
  src/data/mystery-encounters/encounters/field-trip-encounter.ts
  src/data/mystery-encounters/encounters/fiery-fallout-encounter.ts
  src/data/mystery-encounters/encounters/mysterious-chest-encounter.ts
  src/data/mystery-encounters/encounters/the-pokemon-salesman-encounter.ts
  src/data/mystery-encounters/encounters/the-strong-stuff-encounter.ts
  src/data/mystery-encounters/mystery-encounter-pokemon-data.ts
  src/data/mystery-encounters/mystery-encounter.ts
  src/data/mystery-encounters/mystery-encounters.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
  src/enums/battler-tag-type.ts
  src/enums/mystery-encounter-type.ts
  src/field/mystery-encounter-intro.ts
  src/field/pokemon.ts
  src/loading-scene.ts
  src/locales/en/mystery-encounter.ts
  src/locales/en/mystery-encounters/clowning-around-dialogue.ts
  src/phases.ts
  src/system/pokemon-data.ts
  src/test/mystery-encounter/encounters/a-trainers-test-encounter.test.ts
  src/test/mystery-encounter/encounters/absolute-avarice-encounter.test.ts
  src/test/mystery-encounter/encounters/an-offer-you-cant-refuse-encounter.test.ts
  src/test/mystery-encounter/encounters/berries-abound-encounter.test.ts
  src/test/mystery-encounter/encounters/clowning-around-encounter.test.ts
  src/test/mystery-encounter/encounters/delibirdy-encounter.test.ts
  src/test/mystery-encounter/encounters/department-store-sale-encounter.test.ts
  src/test/mystery-encounter/encounters/fiery-fallout-encounter.test.ts
  src/test/mystery-encounter/encounters/fight-or-flight-encounter.test.ts
  src/test/mystery-encounter/encounters/lost-at-sea-encounter.test.ts
  src/test/mystery-encounter/encounters/mysterious-challengers-encounter.test.ts
  src/test/mystery-encounter/encounters/the-pokemon-salesman-encounter.test.ts
  src/test/mystery-encounter/encounters/the-strong-stuff-encounter.test.ts
  src/test/mystery-encounter/encounters/trash-to-treasure-encounter.test.ts
  src/ui/mystery-encounter-ui-handler.ts
Labels: event implementation

#143 reordered biome list and adjusted redirection for project and labels
  .github/ISSUE_TEMPLATE/mystery_event.yml
Labels: enhancement/util

#146 .yml updates
  .github/ISSUE_TEMPLATE/mystery_event.yml
Labels: Enhancement/Util/Misc

#149 Expanded 'Weird Dream' banlist and fixed a bug with the BST bump range
  src/data/mystery-encounters/encounters/weird-dream-encounter.ts
Labels: Bug Report, Balance Adjustment

#153 Migrate translation files to `json`
  src/locales/en/mystery-encounter.ts
  src/locales/en/mystery-encounters/a-trainers-test-dialogue.json
  src/locales/en/mystery-encounters/a-trainers-test-dialogue.ts
  src/locales/en/mystery-encounters/absolute-avarice-dialogue.json
  src/locales/en/mystery-encounters/absolute-avarice-dialogue.ts
  src/locales/en/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
  src/locales/en/mystery-encounters/an-offer-you-cant-refuse-dialogue.ts
  src/locales/en/mystery-encounters/berries-abound-dialogue.json
  src/locales/en/mystery-encounters/berries-abound-dialogue.ts
  src/locales/en/mystery-encounters/clowning-around-dialogue.json
  src/locales/en/mystery-encounters/clowning-around-dialogue.ts
  src/locales/en/mystery-encounters/dancing-lessons-dialogue.json
  src/locales/en/mystery-encounters/dancing-lessons-dialogue.ts
  src/locales/en/mystery-encounters/dark-deal-dialogue.json
  src/locales/en/mystery-encounters/dark-deal-dialogue.ts
  src/locales/en/mystery-encounters/delibirdy-dialogue.json
  src/locales/en/mystery-encounters/delibirdy-dialogue.ts
  src/locales/en/mystery-encounters/department-store-sale-dialogue.json
  src/locales/en/mystery-encounters/department-store-sale-dialogue.ts
  src/locales/en/mystery-encounters/field-trip-dialogue.json
  src/locales/en/mystery-encounters/field-trip-dialogue.ts
  src/locales/en/mystery-encounters/fiery-fallout-dialogue.json
  src/locales/en/mystery-encounters/fiery-fallout-dialogue.ts
  src/locales/en/mystery-encounters/fight-or-flight-dialogue.json
  src/locales/en/mystery-encounters/fight-or-flight-dialogue.ts
  src/locales/en/mystery-encounters/lost-at-sea-dialogue.json
  src/locales/en/mystery-encounters/lost-at-sea-dialogue.ts
  src/locales/en/mystery-encounters/mysterious-challengers-dialogue.json
  src/locales/en/mystery-encounters/mysterious-challengers-dialogue.ts
  src/locales/en/mystery-encounters/mysterious-chest-dialogue.json
  src/locales/en/mystery-encounters/mysterious-chest-dialogue.ts
  src/locales/en/mystery-encounters/part-timer-dialogue.json
  src/locales/en/mystery-encounters/part-timer-dialogue.ts
  src/locales/en/mystery-encounters/safari-zone-dialogue.json
  src/locales/en/mystery-encounters/safari-zone-dialogue.ts
  src/locales/en/mystery-encounters/shady-vitamin-dealer-dialogue.json
  src/locales/en/mystery-encounters/shady-vitamin-dealer-dialogue.ts
  src/locales/en/mystery-encounters/slumbering-snorlax-dialogue.json
  src/locales/en/mystery-encounters/slumbering-snorlax-dialogue.ts
  src/locales/en/mystery-encounters/teleporting-hijinks-dialogue.json
  src/locales/en/mystery-encounters/teleporting-hijinks-dialogue.ts
  src/locales/en/mystery-encounters/the-pokemon-salesman-dialogue.json
  src/locales/en/mystery-encounters/the-pokemon-salesman-dialogue.ts
  src/locales/en/mystery-encounters/the-strong-stuff-dialogue.json
  src/locales/en/mystery-encounters/the-strong-stuff-dialogue.ts
  src/locales/en/mystery-encounters/the-winstrate-challenge-dialogue.json
  src/locales/en/mystery-encounters/the-winstrate-challenge-dialogue.ts
  src/locales/en/mystery-encounters/training-session-dialogue.json
  src/locales/en/mystery-encounters/training-session-dialogue.ts
  src/locales/en/mystery-encounters/trash-to-treasure-dialogue.json
  src/locales/en/mystery-encounters/trash-to-treasure-dialogue.ts
  src/locales/en/mystery-encounters/weird-dream-dialogue.json
  src/locales/en/mystery-encounters/weird-dream-dialogue.ts
  src/test/mystery-encounter/encounters/berries-abound-encounter.test.ts
Labels: Localization
