Repository AsdarDevelops/PokeRogue-Events, pull requests merged in 2024-07, with the labels that each got.

#12 Add more builder methods
  src/data/mystery-encounters/encounters/dark-deal.ts
  src/data/mystery-encounters/encounters/department-store-sale.ts
  src/data/mystery-encounters/encounters/fight-or-flight.ts
  src/data/mystery-encounters/encounters/mysterious-challengers.ts
  src/data/mystery-encounters/encounters/mysterious-chest.ts
  src/data/mystery-encounters/encounters/shady-vitamin-dealer.ts
  src/data/mystery-encounters/encounters/sleeping-snorlax.ts
  src/data/mystery-encounters/encounters/training-session.ts
  src/data/mystery-encounters/mystery-encounter-option.ts
  src/data/mystery-encounters/mystery-encounter-requirements.ts
  src/data/mystery-encounters/mystery-encounter.ts
Labels: enhancement/util

#22 add default label + project to mystery_event.yml
  .github/ISSUE_TEMPLATE/mystery_event.yml
Labels: enhancement/util

#23 clean up mystery_event.yml
  .github/ISSUE_TEMPLATE/mystery_event.yml
Labels: enhancement/util

#31 Update mystery_event.yml
  .github/ISSUE_TEMPLATE/mystery_event.yml
Labels: enhancement/util

#46 Mystery events/dialogue refactoring
  src/battle-scene.ts
  src/battle.ts
  src/data/mystery-encounters/dialogue/dark-deal-dialogue.ts
  src/data/mystery-encounters/dialogue/department-store-sale-dialogue.ts
  src/data/mystery-encounters/dialogue/field-trip-dialogue.ts
  src/data/mystery-encounters/dialogue/fight-or-flight-dialogue.ts
  src/data/mystery-encounters/dialogue/mysterious-challengers-dialogue.ts
  src/data/mystery-encounters/dialogue/mysterious-chest-dialogue.ts
  src/data/mystery-encounters/dialogue/shady-vitamin-dealer.ts
  src/data/mystery-encounters/dialogue/sleeping-snorlax-dialogue.ts
  src/data/mystery-encounters/dialogue/training-session-dialogue.ts
  src/data/mystery-encounters/encounters/dark-deal-encounter.ts
  src/data/mystery-encounters/encounters/dark-deal.ts
  src/data/mystery-encounters/encounters/department-store-sale-encounter.ts
  src/data/mystery-encounters/encounters/department-store-sale.ts
  src/data/mystery-encounters/encounters/field-trip-encounter.ts
  src/data/mystery-encounters/encounters/fight-or-flight-encounter.ts
  src/data/mystery-encounters/encounters/fight-or-flight.ts
  src/data/mystery-encounters/encounters/mysterious-challengers-encounter.ts
  src/data/mystery-encounters/encounters/mysterious-challengers.ts
  src/data/mystery-encounters/encounters/mysterious-chest-encounter.ts
  src/data/mystery-encounters/encounters/mysterious-chest.ts
  src/data/mystery-encounters/encounters/shady-vitamin-dealer-encounter.ts
  src/data/mystery-encounters/encounters/shady-vitamin-dealer.ts
  src/data/mystery-encounters/encounters/sleeping-snorlax-encounter.ts
  src/data/mystery-encounters/encounters/sleeping-snorlax.ts
  src/data/mystery-encounters/encounters/training-session-encounter.ts
  src/data/mystery-encounters/encounters/training-session.ts
  src/data/mystery-encounters/mystery-encounter-dialogue.ts
  src/data/mystery-encounters/mystery-encounter-option.ts
  src/data/mystery-encounters/mystery-encounter.ts
  src/data/mystery-encounters/mystery-encounters.ts
  src/field/mystery-encounter-intro.ts
  src/loading-scene.ts
  src/system/game-data.ts
  src/test/mystery-encounter/mystery-encounter-utils.test.ts
  src/test/vitest.setup.ts
  src/ui/mystery-encounter-ui-handler.ts
Labels: enhancement/util

#47 small bug fixes
  src/battle-scene.ts
  src/phases.ts
  src/phases/mystery-encounter-phase.ts
Labels: enhancement/util

#64 add option mode for UI styling consistency
  src/data/mystery-encounters/encounters/dark-deal-encounter.ts
  src/data/mystery-encounters/encounters/department-store-sale-encounter.ts
  src/data/mystery-encounters/encounters/field-trip-encounter.ts
  src/data/mystery-encounters/encounters/fight-or-flight-encounter.ts
  src/data/mystery-encounters/encounters/mysterious-challengers-encounter.ts
  src/data/mystery-encounters/encounters/mysterious-chest-encounter.ts
  src/data/mystery-encounters/encounters/shady-vitamin-dealer-encounter.ts
  src/data/mystery-encounters/encounters/sleeping-snorlax-encounter.ts
  src/data/mystery-encounters/encounters/training-session-encounter.ts
  src/data/mystery-encounters/mystery-encounter-option.ts
  src/data/mystery-encounters/mystery-encounter.ts
  src/ui/mystery-encounter-ui-handler.ts
Labels: enhancement/util

#68 [Documentation] Event Proposal Guide
  MEs_Proposal_Guide.md
Labels: enhancement/util, balance review, feature discussion

#81 Safari Encounter (Multiple chained option queries) and some sprite offset positioning updates
  public/images/mystery-encounters/bait.json
  public/images/mystery-encounters/bait.png
  public/images/mystery-encounters/chest_blue.json
  public/images/mystery-encounters/chest_blue.png
  public/images/mystery-encounters/mud.json
  public/images/mystery-encounters/mud.png
  src/data/mystery-encounters/encounters/dark-deal-encounter.ts
  src/data/mystery-encounters/encounters/department-store-sale-encounter.ts
  src/data/mystery-encounters/encounters/field-trip-encounter.ts
  src/data/mystery-encounters/encounters/fight-or-flight-encounter.ts
  src/data/mystery-encounters/encounters/mysterious-challengers-encounter.ts
  src/data/mystery-encounters/encounters/mysterious-chest-encounter.ts
  src/data/mystery-encounters/encounters/safari-zone-encounter.ts
  src/data/mystery-encounters/encounters/shady-vitamin-dealer-encounter.ts
  src/data/mystery-encounters/encounters/sleeping-snorlax-encounter.ts
  src/data/mystery-encounters/encounters/training-session-encounter.ts
  src/data/mystery-encounters/mystery-encounter.ts
  src/data/mystery-encounters/mystery-encounters.ts
  src/data/mystery-encounters/utils/encounter-dialogue-utils.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
  src/enums/mystery-encounter-type.ts
  src/field/mystery-encounter-intro.ts
  src/locales/en/battle.ts
  src/locales/en/mystery-encounter.ts
  src/phases.ts
  src/phases/mystery-encounter-phase.ts
  src/pipelines/sprite.ts
  src/test/mystery-encounter/mystery-encounter-utils.test.ts
  src/ui/mystery-encounter-ui-handler.ts
Labels: enhancement/util, event implementation

#37 Implement `Lost at sea` (Common)
  public/images/mystery-encounters/buoy.json
  public/images/mystery-encounters/buoy.png
  src/battle-scene.ts
  src/data/mystery-encounters/encounters/lost-at-sea-encounter.ts
  src/data/mystery-encounters/encounters/mysterious-chest-encounter.ts
  src/data/mystery-encounters/mystery-encounter-option.ts
  src/data/mystery-encounters/mystery-encounter-requirements.ts
  src/data/mystery-encounters/mystery-encounter.ts
  src/data/mystery-encounters/mystery-encounters.ts
  src/data/mystery-encounters/requirements/can-learn-move-requirement.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/enums/mystery-encounter-type.ts
  src/field/mystery-encounter-intro.ts
  src/field/pokemon.ts
  src/locales/en/mystery-encounter.ts
  src/locales/en/mystery-encounters/lost-at-sea.ts
  src/phases/mystery-encounter-phase.ts
  src/test/abilities/quick_draw.test.ts
  src/test/mystery-encounter/encounterTestUtils.ts
  src/test/mystery-encounter/encounters/lost-at-sea-encounter.test.ts
  src/test/utils/gameManager.ts
  src/test/utils/overridesHelper.ts
  src/test/utils/phaseInterceptor.ts
  src/test/utils/testUtils.ts
  src/ui/mystery-encounter-ui-handler.ts
  src/ui/ui.ts
Labels: event implementation
